"use client";
import {useEffect,useRef,type MutableRefObject} from 'react';
import {drawSiege} from '@/lib/debtbreak-siege-render.js';
import {setAim,setTrigger,type SiegeWorld} from '@/lib/debtbreak-siege.js';
import {commandUnproject} from '@/lib/debtbreak-command-view.js';
import {isGrid,GRID_ASSETS,setGridCursor} from '@/lib/debtbreak-command-grid.js';
import {COMMAND_PADS} from '@/lib/debtbreak-command.js';
const paths={ground:'/debtbreak/ground.png',space:'/debtbreak/space.png',atlas:'/debtbreak/atlas.png',sentinel:'/debtbreak/sentinel.png',modules:'/debtbreak/turret-modules.png',impact:'/debtbreak/plasma-impact.png',landscape:'/debtbreak/terrain-v2.png',guns:'/debtbreak/guns-v2.png',districts:'/debtbreak/districts-v2.png',enemies:'/debtbreak/enemies-v2.png'};
type Props={world:MutableRefObject<SiegeWorld>;onReady:()=>void;onFailure:()=>void;onGesture:()=>void;reduced:boolean;onPad?:(pad:number)=>void;onGridPlace?:(id:string,col:number,row:number)=>void;onGridSelect?:(id:string)=>void};
export function DebtbreakSiegeField({world,onReady,onFailure,onGesture,reduced,onPad,onGridPlace,onGridSelect}:Props){
 const pending=useRef<{id:string;col:number;row:number}|null>(null);
 const canvas=useRef<HTMLCanvasElement>(null),images=useRef<Partial<Record<keyof typeof paths,HTMLImageElement>>>({});
 useEffect(()=>{
  let cancelled=false,frame=0;const element=canvas.current,ctx=element?.getContext('2d');if(!element||!ctx){onFailure();return;}
  const load=Object.entries(paths).filter(([key])=>world.current.ledger.continuous?.ground?.command||!['modules','impact','landscape','guns','districts','enemies'].includes(key)).map(([key,path])=>new Promise<void>((resolve,reject)=>{const img=new Image();img.onload=()=>{images.current[key as keyof typeof paths]=img;resolve();};img.onerror=key==='impact'?()=>resolve():reject;img.src=path;}));
  Promise.all(load).then(()=>{if(!cancelled)onReady();}).catch(()=>{if(!cancelled)onFailure();});
  let width=1,height=1;const resize=()=>{const rect=element.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);const dpr=Math.min(1.5,window.devicePixelRatio||1);element.width=Math.round(width*dpr);element.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);};
  const observer=new ResizeObserver(resize);observer.observe(element);resize();
  const draw=()=>{drawSiege(ctx,world.current,width,height,images.current,reduced);frame=requestAnimationFrame(draw);};draw();
  return()=>{cancelled=true;cancelAnimationFrame(frame);observer.disconnect();};
 },[world,onReady,onFailure,reduced]);
 const aim=(e:React.PointerEvent<HTMLCanvasElement>)=>{const rect=e.currentTarget.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width*1000,z=(e.clientY-rect.top)/rect.height*1000;const command=world.current.ledger.continuous?.ground?.command;const p=command&&!isGrid(command)?commandUnproject(x,z):{x,z};setAim(world.current,p.x,p.z);if(isGrid(command))setGridCursor(world.current,{col:Math.floor(x/100),row:Math.floor(z/100)});};
 const release=()=>setTrigger(world.current,'pointer',false);
 const editingGrid=()=>{const c=world.current.ledger.continuous?.ground?.command;return !!c&&isGrid(c)&&['setup','build'].includes(c.stage);};
 const gridDrop=(e:React.DragEvent<HTMLCanvasElement>)=>{e.preventDefault();if(!editingGrid())return;const id=e.dataTransfer.getData('text/plain');if(!GRID_ASSETS.includes(id))return;const rect=e.currentTarget.getBoundingClientRect();onGridPlace?.(id,Math.floor((e.clientX-rect.left)/rect.width*10),Math.floor((e.clientY-rect.top)/rect.height*10));};
 return <canvas ref={canvas} className="siege-canvas" data-grid-placement={editingGrid()?"true":undefined} tabIndex={0} aria-label={world.current.ledger.continuous?.ground?.command?isGrid(world.current.ledger.continuous?.ground?.command)?"Defense grid. Select an asset, then tap a cell. Arrow keys move the placement cursor, Enter places, Escape cancels. Drag pieces between waves. Cash Flow fires automatically; Capital and Credit show coverage.":"Automated base-defense battlefield. Select a gun and tap a build pad during setup, or use the labeled placement selectors. Guns fire automatically within coverage. Enable manual assist to tap ahead of an air missile. P pauses.":world.current.ground?"Ground Defense battlefield. Click or tap a fixed point ahead of an expense missile to launch an area interceptor. Tap an ad to send Sentinel. Arrow keys aim, Space fires, E slashes, P pauses.":"Debtbreak battlefield. Aim with mouse or touch; click for an intercept or hold for rapid fire. Keyboard: arrows aim, Space fires, 1 and 2 choose weapons, E sends Sentinel to slash an ad, P pauses. Tap an ad to send Sentinel."}
  onPointerMove={aim} onPointerDown={e=>{if(e.button!==0)return;aim(e);onGesture();e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);if(editingGrid()){const cursor=world.current.gridCursor!;const occupied=GRID_ASSETS.find(id=>{const p=world.current.ledger.continuous!.ground!.command!.layout?.[id];return p?.col===cursor.col&&p.row===cursor.row;});const id=occupied??world.current.selectedAsset??'cashFlow';if(occupied)onGridSelect?.(occupied);pending.current={id,...cursor};}else if(onPad&&world.current.ledger.continuous!.ground!.command!.stage!=='combat'){const pad=COMMAND_PADS.findIndex(p=>Math.hypot(p.x-world.current.aim.x,p.z-world.current.aim.z)<70);if(pad>=0)onPad(pad);}else if(world.current.ledger.phase==='playing'&&!world.current.ledger.paused)setTrigger(world.current,'pointer',true);}}
  onPointerUp={e=>{if(pending.current&&editingGrid()){aim(e);const p=world.current.gridCursor!;onGridPlace?.(pending.current.id,p.col,p.row);}pending.current=null;release();}} onPointerCancel={()=>{pending.current=null;release();}} onLostPointerCapture={()=>{pending.current=null;release();}}
  onDragOver={e=>{if(editingGrid()){e.preventDefault();e.dataTransfer.dropEffect='move';}}} onDrop={gridDrop}
  onKeyDown={e=>{if(!editingGrid()||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter','Escape'].includes(e.key))return;e.preventDefault();e.stopPropagation();const p=world.current.gridCursor??{col:4,row:4};if(e.key==='Escape'){setGridCursor(world.current,null);pending.current=null;return;}if(e.key==='Enter'){onGridPlace?.(world.current.selectedAsset??'cashFlow',p.col,p.row);return;}setGridCursor(world.current,{col:Math.max(2,Math.min(7,p.col+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0))),row:Math.max(2,Math.min(7,p.row+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)))});}} onContextMenu={e=>e.preventDefault()}/>;
}
