"use client";
import {useState,useRef} from 'react';
import {Crosshair,Home,Pause,Play,RotateCcw,Volume2,VolumeX,Vault,Zap,Layers,PiggyBank,Wrench,Droplets,Bed,Shirt,Heart,Users,Compass,Radar,Swords} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {DebtbreakSiegeField} from './debtbreak-siege-field';
import {useDebtbreakerController} from './debtbreaker-controller';
import type {AvatarKind,AvatarVisualState,CornerStrengths} from './avatar-stage';
import type {Snapshot} from '@/lib/vision-contract.js';
import type {ResolvedDetails} from '@/lib/advanced-finances.js';
import {shotValue} from '@/lib/debtbreaker-engine.js';
import {radarSeconds} from '@/lib/debtbreak-siege.js';
import {accountDebt,continuousOutflow,continuousSummary,basePlan,lifestyleCoverage,lifestyleOutflow,lifestyleRequirements,LIFESTYLE_TIERS,capitalShield,DAY_SECONDS,type LedgerAction} from '@/lib/debtbreak-continuous.js';
import {INTERRUPTION_NOTICE} from '@/lib/debtbreak-clock.js';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n%100?2:0}).format(n/100);
const lifestyle=[['Air · water · food',Droplets],['Shelter · safety',Home],['Sleep',Bed],['Clothing',Shirt],['Health care',Heart],['Socializing',Users],['Purpose',Compass]] as const;
type Props={avatar:AvatarKind;strengths:CornerStrengths;hangar:Snapshot;visualState:AvatarVisualState;details?:ResolvedDetails;onExit:()=>void;onChallenges:()=>void;onClassic:()=>void};
function Facts({rows}:{rows:[string,string][]}){return <dl className="db31-facts">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;}
export function DebtbreakerTurret({hangar,visualState,details,onExit,onChallenges,onClassic}:Props){
 const game=useDebtbreakerController(hangar,visualState.creditGrade,details),{state,world}=game,c=state.continuous!;
 const [pace,setPace]=useState('standard'),[fictional,setFictional]=useState(false),[goalMonths,setGoalMonths]=useState(3);
 const [panel,setPanel]=useState<'tactical'|'help'|null>(null),[leaveAction,setLeaveAction]=useState<(()=>void)|null>(null);
 const [amount,setAmount]=useState('100'),[funding,setFunding]=useState<'income'|'reserve'>('reserve'),serial=useRef(0);
 const cents=Math.round(Number(amount)*100),valid=Number.isSafeInteger(cents)&&cents>0&&cents<=1e11;
 const summary=continuousSummary(state),outflow=continuousOutflow(state),plan=basePlan(state),shot=shotValue(state);
 const coverage=lifestyleCoverage(state),shield=capitalShield(state);
 const [tier,setTier]=useState(2),[adjustable,setAdjustable]=useState(String(c.lifestyle.adjustable/100));
 const allowance=Math.round(Number(adjustable)*100),baselineLiving=c.lifestyle.baseline.reduce((n,e)=>n+e.amount,0);
 const validAllowance=Number.isSafeInteger(allowance)&&allowance>=0&&allowance<=Math.floor(baselineLiving/2),nextOutflow=validAllowance?lifestyleOutflow(state,tier,allowance):outflow;
 const sentinel=world.current.sentinel,swordBusy=sentinel.mode==='dash'||sentinel.mode==='swing'||sentinel.cooldown>0;
 const terminal=['complete','gameover'].includes(state.phase),playing=state.phase==='playing',briefing=state.phase==='briefing';
 const source=world.current.source,weapon=world.current.weapon;
 const targets=state.threats.filter(t=>t.lane!=='reserve'&&t.lane!=='want'&&t.remaining>0);
 const nextDue=[...targets].sort((a,b)=>a.dueDay!-b.dueDay!)[0];
 const repair=state.defenses.find(d=>d.owned&&d.condition<(d.maxCondition??100));
 const repairPoints=repair?Math.min(10,(repair.maxCondition??100)-repair.condition,Math.floor(Math.max(0,state.reserves)/1000)):0;
 const rescueTarget=state.threats.find(t=>t.id===c.rescue?.targetId);
 const progress=summary.planned?Math.min(100,summary.paid/Math.max(1,summary.planned-summary.adjustment)*100):100;
 const condition=state.defenses.reduce((n,d)=>n+d.condition,0),maxCondition=state.defenses.reduce((n,d)=>n+(d.maxCondition??100),0);
 const act=(a:LedgerAction)=>game.action({...a,id:`ui:${++serial.current}`});
 const openPanel=(kind:typeof panel)=>{if(kind==='tactical'){setTier(c.lifestyle.pending?.tier??c.lifestyle.tier);setAdjustable(String((c.lifestyle.pending?.adjustable??c.lifestyle.adjustable)/100));}game.pause();game.setModal(!!kind);setPanel(kind);};
 const leave=(fn:()=>void)=>{if(playing){game.pause();game.setModal(true);setLeaveAction(()=>fn);}else fn();};
 const closeLeave=()=>{game.setModal(false);setLeaveAction(null);};
 const offers=c.offers.filter(o=>o.status==='offered');
 const grade=c.fictional?'C · example':state.hangar?.grade??'Unknown';
 return <div className="sector-shell siege-shell" data-phase={state.phase}>
  <header className="siege-header"><span>VI$ION GAMES</span><h2>DEBT<span>BREAK</span></h2><nav aria-label="Game navigation"><Button variant="ghost" onClick={()=>leave(onChallenges)}>Challenges</Button><Button variant="ghost" onClick={()=>leave(onClassic)}>Classic</Button><Button variant="ghost" onClick={()=>leave(onExit)}><Home size={16}/><span>Hangar</span></Button></nav></header>
  <div className="siege-objective"><strong>{coverage.complete?'DEFEND YOUR LIFESTYLE':'BUILD TO COVER YOUR LIFESTYLE'}</strong><span>Cycle {state.period}/4 · Day {Math.min(30,c.day-(state.period-1)*30+1)}/30</span><span className="siege-cycle-pips" aria-label={`Cycle ${state.period} of 4`}>{[1,2,3,4].map(n=><b key={n} data-current={n===state.period} data-done={n<state.period}>{n<state.period?'✓':n}</b>)}</span></div>
  <div className="siege-coverage"><span>{LIFESTYLE_TIERS[c.lifestyle.tier]} lifestyle <b>{coverage.active}/{coverage.required} sections protected</b></span><progress aria-label="Lifestyle coverage" value={coverage.active} max={coverage.required}/><strong>{coverage.percent}%</strong><small>{coverage.complete?'Hold through cycle 4 · keep bills covered':'Expand the base beneath all seven needs'}</small></div>
  <div className="siege-progress"><span>BILLS COVERED <b>{money(summary.paid)} / {money(summary.planned-summary.adjustment)}</b></span><progress value={progress} max="100" aria-label="Bills covered this cycle"/><strong>{Math.round(progress)}%</strong><span>{nextDue?`${nextDue.overdue?'OVERDUE':'NEXT DUE'}: ${nextDue.overdue?money(state.arrears):`${Math.max(0,nextDue.dueDay!-c.day)} DAYS`}`:'BILLS CLEAR'}</span></div>
  <div className="siege-balances"><div><Zap/><span>INCOME AMMO</span><b data-testid="income-balance">{money(state.incomeWallet)}</b></div><div><Vault/><span>RESERVES</span><b data-testid="reserve-balance">{money(state.reserves)}</b></div><div><Radar/><span>CREDIT</span><b>{grade}</b></div></div>
  <main className="siege-battlefield" aria-label="Interactive Debtbreak battlefield">
   <DebtbreakSiegeField key={game.sceneKey} world={world} onReady={game.onReady} onFailure={game.onFailure} onGesture={game.gesture} reduced={game.reduced}/>
   <div className="siege-field-top"><span>UTILITANKS · LIVING COSTS</span><button onClick={()=>openPanel('help')}>Radar · {radarSeconds(state).toFixed(1)}s warning</button></div>
   {playing&&!state.paused&&<div className="siege-field-facts"><button onClick={()=>act({type:'protect',enabled:!c.autoProtect})}>Reserve protection <b>{c.autoProtect?'ON':'OFF'}</b></button><span>Shield {shield.charged?'CHARGED · 25% less breach damage':`${money(state.reserves)} / ${money(plan.goal)}`}</span><span>Armor {Math.round(condition/Math.max(1,maxCondition)*100)}% · Base {coverage.active}/{coverage.required}</span></div>}
   {playing&&c.rescue&&<div className="siege-rescue" role="alert"><strong>FINAL DEFENSE DOWN · {Math.ceil(c.rescue.remainingSeconds)}s {state.paused?'PAUSED':''}</strong><span>Repair or cover {c.rescue.label}. Another breach ends the mission.</span><div>{(['income','reserve'] as const).map(wallet=>{const available=Math.max(0,wallet==='income'?state.incomeWallet:state.reserves);return <span key={wallet}><Button disabled={!repair||available<1000} onClick={()=>act({type:'repair',source:wallet,points:1})}>Repair $10 · {wallet}</Button><Button disabled={!rescueTarget||!available} onClick={()=>act({type:'pay',source:wallet,targetId:rescueTarget?.id,amount:Math.min(available,rescueTarget?.remaining??0)})}>Pay · {wallet}</Button></span>;})}<Button onClick={()=>openPanel('tactical')}>Pause &amp; review</Button></div></div>}
   {!game.ready&&!game.failed&&<div className="siege-loading">Loading battlefield…</div>}
   {briefing&&<section className="siege-brief"><span className="eyebrow">SENTINEL DEFENSE</span><h3>Build a base.<br/>Protect a lifestyle.</h3><p>Marching bills. Incoming debt. Optional wants. Build enough base to cover your lifestyle. Finish early if you can, then defend it and cover required payments through all four cycles.</p><div className="siege-brief-rules"><span><b>1 · INTERCEPT</b> Click a debt missile for one precise payment.</span><span><b>2 · RAPID FIRE</b> Hold to pay down marching Utilitanks.</span><span><b>BUILD</b> Cover issued bills, then expand. Reserve goals power up your shield.</span><span><b>SWORD</b> Tap an ad. One strike clears it. Every five clears charge a wider sweep.</span></div><div className="siege-setup"><label>Mission<Select value={fictional?'fictional':'picture'} onValueChange={v=>setFictional(v==='fictional')}><SelectTrigger aria-label="Mission"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="picture">My hangar picture</SelectItem><SelectItem value="fictional">Fictional example</SelectItem></SelectContent></Select></label><label>Pace<Select value={pace} onValueChange={setPace}><SelectTrigger aria-label="Mission pace"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="relaxed">Relaxed · 3s/day</SelectItem><SelectItem value="standard">Standard · 2s/day</SelectItem><SelectItem value="pressure">Pressure · 1.5s/day</SelectItem></SelectContent></Select></label><label>Reserve goal<Select value={String(goalMonths)} onValueChange={v=>setGoalMonths(Number(v))}><SelectTrigger aria-label="Reserve goal"><SelectValue/></SelectTrigger><SelectContent>{[1,3,6].map(n=><SelectItem value={String(n)} key={n}>{n} {n===1?'month':'months'} of outflow</SelectItem>)}</SelectContent></Select></label></div><p className="siege-note">{fictional?'Fictional debts: 8% loan and 24% card.':`${money(state.startingIncome)} income · ${money(outflow)} required per cycle.`} {DAY_SECONDS[pace]} seconds = one modeled day. Pause anytime.</p>{!fictional&&(!!details?.issues.length||!!c.issues.length)&&<p role="alert">{[...(details?.issues??[]),...c.issues].join(' ')}</p>}<Button className="siege-start" disabled={!game.ready||!fictional&&(!!details?.issues.length||!!c.issues.length)} onClick={()=>game.start(pace,fictional,goalMonths)}><Play/>START DEBTBREAK</Button><button className="siege-text-button" onClick={()=>openPanel('help')}>How payments, warnings and protection work</button></section>}
   {playing&&state.paused&&panel===null&&<div className="siege-paused"><h3>{game.failed?'Battlefield unavailable':state.notice===INTERRUPTION_NOTICE?'Play interrupted':'PAUSE / PLAN'}</h3><p>{state.notice===INTERRUPTION_NOTICE?'A long interruption paused play. Resume when ready.':'Time, missiles and rescue countdown are frozen.'}</p><div><Button disabled={!game.ready} onClick={game.toggle}><Play/>Resume</Button><Button variant="outline" onClick={()=>openPanel('tactical')}>Pay · deposit · review</Button></div></div>}
   {game.failed&&briefing&&<div className="siege-paused"><h3>Battlefield could not load</h3><p>Reload the game to try loading its artwork again.</p><Button onClick={onExit}>Return to hangar</Button></div>}
   {terminal&&<div className="siege-ending"><span className="eyebrow">{state.phase==='complete'?(c.mission?.success?'MISSION COMPLETE':'MISSION INCOMPLETE'):'GAME OVER'}</span><h3>{state.phase==='complete'?(c.mission?.success?'Lifestyle protected.':'Four cycles. More to build.'):'The final protection failed.'}</h3><p>{state.phase==='gameover'?state.gameOverReason:`${coverage.active}/${coverage.required} ${LIFESTYLE_TIERS[c.lifestyle.tier].toLowerCase()} lifestyle sections protected · ${money(summary.unpaid)} obligations still unpaid.`}</p><Facts rows={[["Bills paid",money(summary.livingPaid+summary.debtPaid)],["Repairs / expansion",`${money(summary.repairs)} / ${money(summary.expansions)}`],["Optional wants",money(summary.purchases)],["Available reserves",money(state.reserves)],["Cash reconciliation difference",money(summary.cashDifference)]]}/><div><Button onClick={game.reset}><RotateCcw/>Replay</Button><Button variant="outline" onClick={()=>openPanel('tactical')}>Mission ledger</Button><Button variant="ghost" onClick={onExit}>Hangar</Button></div></div>}
  </main>
  <div className="siege-lifestyle" aria-label="Seven lifestyle needs and their game base coverage">{lifestyle.map(([name,Icon],i)=>{const area=coverage.areas[i],protectedNow=area.active===area.required;return <div key={name} data-built={protectedNow} title={`${name}: ${area.active}/${area.required} protected sections`}><Icon/><b>{name}</b><span>{area.active}/{area.required} protected</span><progress value={area.condition} max={area.maximum} aria-label={`${name}: game wall condition`}/></div>;})}</div>
  <div className="siege-sentinel" data-power-ready={sentinel.charges>0}><span><Swords size={18}/><b>SENTINEL</b><small>{sentinel.charges>0?`POWER SWEEP READY · ${sentinel.charges} charged`:swordBusy?(sentinel.queuedId?'Next ad queued':'Target locked · one strike'):'Tap an ad to slash'} <span className="siege-sword-meter">{sentinel.cleared} cleared · {sentinel.cleared%5}/5 to power sweep</span></small></span><button disabled={!playing||state.paused} onClick={()=>game.sword()}>{sentinel.charges>0?'E · POWER SWEEP':'E · SLASH AD'}</button><button disabled={!playing} onClick={()=>openPanel('tactical')}>Adjust lifestyle</button></div>
  <div className="siege-funding"><span>SHOT FUNDING</span><div role="group" aria-label="Shot funding">{(['auto','income','reserve'] as const).map(v=><button key={v} disabled={!playing} aria-pressed={source===v} onClick={()=>game.source(v)}>{v==='reserve'?'RESERVES':v.toUpperCase()}</button>)}</div><span>IN FLIGHT <b>{money(summary.held)}</b></span><button disabled={!playing} onClick={()=>openPanel('tactical')}>Accounts · {targets.length} unpaid</button></div>
  <div className="siege-weapons"><button disabled={!playing} aria-pressed={weapon==='intercept'} onClick={()=>game.weapon('intercept')}><Crosshair/><span><b>1 · INTERCEPT</b><small>Single shot · up to {money(shot*4)}</small></span></button><button disabled={!playing} aria-pressed={weapon==='rapid'} onClick={()=>game.weapon('rapid')}><Zap/><span><b>2 · RAPID FIRE</b><small>Hold fire · up to {money(shot)} / shot</small></span></button><button disabled={!playing||state.paused||!game.ready} className="siege-fire" onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);game.fire(true);}} onPointerUp={()=>game.fire(false)} onPointerCancel={()=>game.fire(false)} onLostPointerCapture={()=>game.fire(false)} onClick={e=>{if(e.detail===0)game.pulse();}}><Crosshair/><span><b>FIRE</b><small>{weapon==='intercept'?'Tap to intercept':'Hold to fire'}</small></span></button><button disabled={!playing} onClick={()=>openPanel('tactical')}><Pause/><span><b>PAUSE / PLAN</b><small>Pay · deposit · review</small></span></button></div>
  <div className="siege-build"><div><span>PLAN WITH SURPLUS</span><small>Game purchases reduce reserves. {money(plan.uncovered)} set aside for uncovered bills.</small></div><div><button disabled={!playing||!repairPoints} onClick={()=>act({type:'repair',source:'reserve',points:10})}><Wrench/><span><b>REPAIR · {money(repairPoints*1000)}</b><small>+{repairPoints} condition</small></span></button><button disabled={!playing||!plan.canExpand} title={`Needs ${money(plan.cost)} after ${money(plan.uncovered)} uncovered bills`} onClick={()=>act({type:'expand',source:'reserve'})}><Layers/><span><b>{c.base.expansions>=coverage.required?'BASE BUILT':`EXPAND WALL · ${money(plan.cost)}`}</b><small>+25 condition · {Math.min(c.base.expansions,coverage.required)}/{coverage.required} built</small></span></button><button disabled={!playing} onClick={()=>{setFunding('income');openPanel('tactical');}}><PiggyBank/><span><b>KEEP SAVINGS</b><small>Deposit income · build a buffer</small></span></button></div></div>
  {playing&&offers.length>0&&<div className="siege-offers"><span>WANT-BOTS · {offers.length} optional choices</span>{offers.slice(0,2).map(o=><div key={o.id}><b>{o.label} · {money(o.cost)}</b><button disabled={state.paused} onClick={()=>game.sword(o.id)}>Sword · free</button><button onClick={()=>openPanel('tactical')}>Review / buy</button></div>)}</div>}
  <footer className="siege-footer"><span role="status">{state.notice}</span><div><button aria-pressed={world.current.assist} onClick={game.assist}>Assist {world.current.assist?'on':'off'}</button><button disabled={weapon!=='rapid'||!playing||state.paused} aria-pressed={world.current.autoFire} onClick={game.auto}>Auto {world.current.autoFire?'on':'off'}</button><button aria-label={game.sound?'Mute sound':'Enable sound'} onClick={game.toggleSound}>{game.sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button onClick={()=>openPanel('help')}>Controls</button></div></footer>
    <Dialog open={panel!==null} onOpenChange={open=>{if(!open)openPanel(null);}}><DialogContent className="dbt-info-dialog dbc-dialog"><DialogHeader><DialogTitle>{panel==='help'?'Debtbreak controls':terminal?'Mission ledger':'Tactical Pause · accounts & actions'}</DialogTitle><DialogDescription>{terminal?'Final account and cash records.':'Time is frozen. Explicit actions below execute once without advancing the day.'}</DialogDescription></DialogHeader>
      {panel==='help'?<div className="db31-help"><p>Mouse aims. Intercept fires once per click; Rapid Fire repeats while held. Touch: aim on the field, then tap or hold FIRE. Keyboard: arrows / WASD aim, Space fires, 1 selects Intercept, 2 selects Rapid Fire, R cycles funding, P pauses. Tap a Want-bot or press E to send Sentinel; he runs to the ad and swings when it reaches sword range. One connected strike clears one ad. Tap another ad while he is busy to queue it. Every five sword clears charge a wider sweep for the next strike; nearby ads can be cleared together. His recovery and queued target freeze on pause. Controller: stick aims, right trigger fires, A income / B reserves, shoulder buttons choose weapon, Start pauses.</p><p>Assist follows a target you select. Autofire fires toward your reticle; it starts off. Rapid Fire commits up to {money(shot)} per shot; Intercept pays up to {money(shot*4)} per click from one wallet. Misses refund that same wallet. Sword attacks reject wants without spending or earning money or credit. The paused planner also offers a free Pass action.</p><p>Reserve protection is scheduled one modeled day before due dates. Faster enemies can reach the base before a bill is due. A contact uses available reserve protection or damages game armor; it does not make a bill overdue or post an early fee. Surviving unpaid obligations return for another attack. Bill due dates, fees, and interest still follow the normal calendar. These are arcade effects, not new debt or cash charges.</p><p>Debtonators grow with modeled interest and fees. Multiple bodies share one obligation; they do not multiply debt. Credit radar gives 1–6 seconds of game warning, highlighting known rates of 18% APR or more. Unknown APR stays unknown. Radar is a game metaphor, not a claim that credit scores predict incoming debt. Pay extra deliberately in Accounts after that account’s issued requirements are covered.</p></div>:<div className="dbc-tactical">
        <Facts rows={[["Available income",money(state.incomeWallet)],["Available reserves",money(state.reserves)],["Money committed to projectiles",money(summary.held)],["Current overdue claims",money(state.arrears)],["Cash reconciliation difference",money(summary.cashDifference)]]}/>
        {!terminal&&<section className="dbc-actions"><label>Transaction amount ($)<Input aria-label="Transaction amount" type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="db31-options" role="group" aria-label="Transaction funding"><button aria-pressed={funding==='income'} onClick={()=>setFunding('income')}>Income</button><button aria-pressed={funding==='reserve'} onClick={()=>setFunding('reserve')}>Reserves</button></div><Button disabled={!valid} onClick={()=>act({type:'deposit',amount:cents,source:'income'})}>Deposit up to {valid?money(cents):'$0'} from income</Button><Button variant="outline" disabled={!valid||!repair} onClick={()=>act({type:'repair',source:funding,points:Math.floor(cents/1000)})}>Repair · up to {valid?Math.floor(cents/1000):0} points</Button><label className="dbc-check"><Checkbox checked={c.autoProtect} onCheckedChange={v=>act({type:'protect',enabled:v===true})}/><span>Automatic reserve protection</span></label></section>}
        <h4>Base planning</h4><p>Win by covering the active lifestyle footprint and paying all issued requirements through cycle four. Building early changes your task to defending it. Any required wall at zero condition needs repair.</p><p>Reserve goal: {c.base.goalMonths} months · {money(plan.goal)}. Uncovered bills set-aside: {money(plan.uncovered)}. Investable surplus: {money(plan.surplus)}.</p><p>Each {money(plan.cost)} expansion adds 25 game condition, with no added upkeep or resale value. Essential / Current / Expanded lifestyles require 7 / 10 / 14 sections across the same seven needs. Reaching the reserve goal reduces arcade breach damage by 25% while reserves stay at the goal. It does not cancel bills.</p>{!terminal&&<Button disabled={!plan.canExpand} onClick={()=>act({type:'expand',source:'reserve'})}>Expand wall · {money(plan.cost)}</Button>}
        <section className="siege-lifestyle-plan"><h4>Lifestyle plan · {LIFESTYLE_TIERS[c.lifestyle.tier]} active</h4><p>Change future living costs and the base footprint together. All seven needs remain. Your original hangar data and already issued bills stay unchanged.</p><p className="siege-note">Prototype assumption: 20% of starting living costs is adjustable by default. Set the amount below, including $0. This is a scenario assumption, not verified savings or a measure of wellbeing.</p>{!terminal&&<><div className="siege-plan-inputs"><label>Lifestyle tier<Select value={String(tier)} onValueChange={v=>setTier(Number(v))} disabled={state.period===4}><SelectTrigger aria-label="Lifestyle tier"><SelectValue/></SelectTrigger><SelectContent>{[1,2,3].map(n=><SelectItem key={n} value={String(n)}>{LIFESTYLE_TIERS[n]} · {lifestyleRequirements(n).reduce((a,b)=>a+b,0)} sections</SelectItem>)}</SelectContent></Select></label><label>Adjustable living costs per cycle ($)<Input aria-label="Adjustable living costs" type="number" min="0" max={baselineLiving/200} step="0.01" value={adjustable} disabled={state.period===4} onChange={e=>setAdjustable(e.target.value)}/></label></div><p>Current outflow <b>{money(outflow)}</b> → next cycle <b>{validAllowance?money(nextOutflow):'Enter a valid amount'}</b>. {validAllowance&&`${money(outflow-nextOutflow)} more cash flow per future cycle.`} No sale proceeds or refunds.</p>{!validAllowance&&<p role="alert">Enter $0 to {money(Math.floor(baselineLiving/2))}.</p>}<Button disabled={!validAllowance||state.period===4} onClick={()=>act({type:'lifestyle',tier,amount:allowance})}>Apply from cycle {Math.min(4,state.period+1)}</Button>{state.period===4&&<p>Final cycle locked. Explore another lifestyle on replay.</p>}</>}{c.lifestyle.pending&&<p role="status">Queued: {LIFESTYLE_TIERS[c.lifestyle.pending.tier]} for cycle {state.period+1} · {money(lifestyleOutflow(state,c.lifestyle.pending.tier,c.lifestyle.pending.adjustable))} outflow. <button className="siege-text-button" onClick={()=>act({type:'cancelLifestyle'})}>Cancel change</button></p>}</section>
        <h4>Want-bot choices</h4>{offers.map(o=><article className="dbc-account" key={o.id}><strong>{o.label} · {money(o.cost)} · +{o.reward} enjoyment</strong><div><Button onClick={()=>act({type:'reject',offerId:o.id})}>Pass · free</Button><Button disabled={state.incomeWallet<o.cost||terminal} onClick={()=>act({type:'buy',offerId:o.id,source:'income'})}>Buy · income</Button><Button disabled={state.reserves<o.cost||terminal} onClick={()=>act({type:'buy',offerId:o.id,source:'reserve'})}>Buy · reserves</Button></div></article>)}
        <h4>Issued requirements</h4>{targets.filter(t=>t.lane!=='reserve').map(t=><article className="dbc-account" key={t.id}><strong>{t.label} · cycle {t.cycle}</strong><p>{money(t.remaining)} remaining · due absolute day {t.dueDay}{t.overdue?' · overdue':''}{t.late30?' · 30-day late history':''}</p>{!terminal&&<Button variant="outline" disabled={!valid} onClick={()=>act({type:'pay',targetId:t.id,amount:cents,source:funding})}>Pay up to {valid?money(cents):'$0'} · {funding}</Button>}</article>)}
        <h4>Account generators · remaining debt</h4>{c.accounts.map(a=><article className="dbc-account" key={a.id}><h4>{a.name}</h4><p>{a.method==='payments'?'Payments only · balance not projected':a.method==='daily-v1'?'Daily game estimate · simple 30/360 · rate held constant':'Existing monthly estimate · opening principal × rate / 12'}</p><Facts rows={[["Modeled balance",a.method==='payments'?'Not projected':money(accountDebt(a)!)],["Unpaid interest / fees",a.method==='payments'?'Unknown':`${money(a.interest)} / ${money(a.fees)}`],["Timing",`${a.timingKnown?'Entered':'Scenario'} due day ${a.dueDay}`],["Late-fee rule",a.lateFee===null?'Unknown · not estimated':`${money(a.lateFee)} after ${a.feeDelay} delay days`],["History",a.lateHistory?'Reached 30 modeled days past due; credit grade unchanged':'No 30-day late event'] ]}/>{a.payoffDay!==null?<strong>Modeled payoff · day {a.payoffDay}. Linked costs continue.</strong>:!terminal&&a.method!=='payments'&&<Button variant="outline" disabled={!valid||targets.some(t=>t.accountId===a.id&&t.remaining>0)} onClick={()=>act({type:'extra',accountId:a.id,amount:cents,source:funding})}>Pay extra · up to {valid?money(cents):'$0'} · {funding}</Button>}</article>)}
        {!!c.summaries.length&&<><h4>Closed cycles</h4>{c.summaries.map(s=><p key={s.cycle}>Cycle {s.cycle}: {money(s.paid)} paid · {money(s.unpaid)} unpaid at close · {s.onTime?"all requirements covered on time":"some requirements missed their due date"} · {money(s.reserves)} reserves</p>)}</>}
        <h4>Transaction log</h4><ol className="dbc-log">{c.log.slice().reverse().map(l=><li key={l.id}><b>Day {l.day}</b> {l.text}</li>)}</ol><p className="db31-note">Required payments are claims on account balances, not extra debt. Living arrears stay separate. Cash check includes both wallets, in-flight funds, payments, repairs, expansions and purchases. Transfers count once.</p>
      </div>}<Button onClick={()=>openPanel(null)}>Close</Button></DialogContent></Dialog>
    <Dialog open={!!leaveAction} onOpenChange={open=>{if(!open)closeLeave();}}><DialogContent className="dbt-info-dialog"><DialogHeader><DialogTitle>Leave this mission?</DialogTitle><DialogDescription>This ends the current simulation. Your hangar picture stays unchanged.</DialogDescription></DialogHeader><Button variant="outline" onClick={closeLeave}>Cancel</Button><Button onClick={()=>{leaveAction?.();closeLeave();}}>Leave mission</Button></DialogContent></Dialog>
  </div>;
}
