import type { DebtbreakerState, Threat } from './debtbreaker-engine.js';
export type CombatEvent = {serial:number;type:string;x:number;z:number;amount:number;targetId:string|null;actorId:string|null;born:number};
export type Drone = {id:string;targetId:string;slot:number;remaining:number};
export type CombatActor = {id:string;target:Threat;slot:number;index:number;remaining:number;x:number;z:number;radius:number};
export type CombatWorld = {ledger:DebtbreakerState;drones:Drone[];formationPeriod:number;settleUntil:number;pace:string;time:number;angle:number;aim:{x:number;z:number};firing:boolean;source:'income'|'reserve';autoFire:boolean;assist:boolean;lockedId:string|null;hoveredId:string|null;triggers:Record<string,boolean>;pendingShot:boolean;cooldown:number;bullets:{id:number;x:number;z:number;dx:number;dz:number;source:'income'|'reserve';travel:number}[];effects:CombatEvent[];events:CombatEvent[];serial:number;shots:number;hits:number;misses:number};
export const TURRET: {x:number;z:number};
export const VAULT: {x:number;z:number};
export const CADENCE:number;
export const BULLET_SPEED:number;
export const PACES:Record<string,number>;
export const SQUAD_SIZE:number;
export function createCombat(ledger:DebtbreakerState,pace?:string):CombatWorld;
export function targetPosition(target:{lane:string;progress:number},time:number,index?:number,slot?:number,defenseIndex?:number):{x:number;z:number;radius:number};
export function defenseContact(lane:string,slot?:number,defenseIndex?:number):{x:number;z:number};
export function combatActors(world:CombatWorld,time?:number):CombatActor[];
export function advanceCombat(world:CombatWorld,seconds:number):CombatWorld;
export function clearTriggers(world:CombatWorld):void;
export function setTrigger(world:CombatWorld,source:string,active:boolean):void;
export function setAim(world:CombatWorld,x:number,z:number):void;
export function aimAtTarget(world:CombatWorld,id:string):void;
export function segmentHit(ax:number,az:number,bx:number,bz:number,cx:number,cz:number,radius:number):number|null;
export function wrapAngle(angle:number):number;
