export type Debt = { id: string; name: string; balance: number; apr: number; payment: number; due: string };
export type Ledger = { period: number; income: number; living: number; minimums: number; reserves: number; carry: number; repairDue: number; interestPosted: number; assistIndex: number; campaignDebt: number; assistProgress: number; debts: Debt[]; challenge?: import('./debtbreak-challenges').ChallengeState };
export type Strategy = "snowball" | "avalanche";
export type Bonus = { id: string; share: number; multiplier: number; seconds: number; pillar: number };
export type Plan = { start: Ledger; ledger: Ledger; strategy: Strategy; savings: number; budget: number; remaining: number; executed: number; reserveLimit: number; reserveRemaining: number; reserveSpent: number; orderedPaid: number; outOfOrderPaid: number; targetId: string | null; cleared: string[]; bonuses: Bonus[]; event: null | { name: string; cost: number; covered: number; shortfall: number }; settled: boolean; nextLedger: Ledger | null };
export const PILLAR_NAMES: string[];
export function copy<T>(value: T): T;
export function practiceScenario(): Ledger;
export function totalDebt(ledger: Ledger): number;
export function requiredPayments(ledger: Ledger): number;
export function periodSurplus(ledger: Ledger): number;
export function availableFunds(ledger: Ledger): number;
export function sequence(ledger: Ledger, strategy: Strategy, lockedId?: string | null): Debt[];
export function interestEstimate(ledger: Ledger): number;
export function reserveMilestone(ledger: Ledger): { months: number; next: number | null; goal: number | null; progress: number };
export function startPlan(start: Ledger, savings: number, strategy: Strategy, reserveLimit?: number): Plan;
export function repay(plan: Plan, accountId: string, requested: number, source?: 'cash' | 'reserves'): null | { amount: number; source: string; correct: boolean; cleared: boolean; freed: number; bonus: Bonus | null };
export function projection(start: Ledger, savings: number, strategy: Strategy): { ledger: Ledger; unused: number; interest: number; interestSaved: number; freed: number; nextSurplus: number };
export function settlePeriod(plan: Plan): Plan;
export function nextPeriod(plan: Plan): Ledger;
export function practiceInputs(ledger: Ledger): import('./vision-contract').CurrentInputs;
