import type { Ledger, Plan } from './debtbreak-finance';
export type ChallengeId = 'cash-flow' | 'capital' | 'collateral' | 'credit' | 'four-corners';
export type Choices = { equipment: string; funding: string };
export type ChallengeState = { id: ChallengeId; duration: number; initialDebt: number; initialPayments: number; reserveGoal: number; asset: { owned: boolean; condition: number; pledgedTo: string | null }; repairComplete: boolean; paymentPeriods: number; overdue: number; salePending: number; costs: number; reserveUsed: number; soldFor: number; notes: string[]; lastChoice: Choices | null; supportSeconds: number; emergencyCovered: number; emergencyShortfall: number };
export type Challenge = { id: ChallengeId; name: string; title: string; color: string; icon: string; lesson: string; objective: string; mechanic: string; event: string };
export const CHALLENGES: Challenge[];
export function challengeInfo(id: string): Challenge | undefined;
export function challengeScenario(id: ChallengeId): Ledger;
export function defaultChoices(ledger: Ledger): Choices;
export function hasEquipment(id: ChallengeId): boolean;
export function hasOffers(id: ChallengeId): boolean;
export function equipmentOnline(ledger: Ledger): boolean;
export function assetValue(ledger: Ledger): number;
export type Offer = { id: string; label: string; apr: number; secured: boolean; principal: number; payment: number; months: number; total: number; lastPayment: number; cost: number; improved: boolean };
export function financingOffers(ledger: Ledger): Offer[];
export function saleQuote(ledger: Ledger): { gross: number; fee: number; lien: number; net: number };
export function prepareChallenge(start: Ledger, choices: Choices): { ledger: Ledger; error: string | null };
export function settleChallengePeriod(plan: Plan): Plan;
export function advanceChallengePeriod(plan: Plan): Ledger;
export type Outcome = { debtReduced: number; freed: number; surplus: number; reserves: number; condition: number; liquid: number; online: boolean; passed: boolean; checks: { label: string; passed: boolean }[] };
export function challengeOutcome(ledger: Ledger): Outcome;
